project_id = "njaylytxqksoibyiijms"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.wa-test]
verify_jwt = false

[functions.activate-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false
